import uuid from "react-native-uuid";


export const exercises = [
{
  id: uuid.v4(),
  image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/XcWkkbv5tOPEfVvQjHTQ.png",
    name: "Courir sur place",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 1 : Échauffements",
    body_part: "Séance Full Body",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/IJPPP5tNWFF3CDwtqe1k.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 30,
  status: 'Tout'

},
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/mVzTmvvOOmrZkIpvOl2U.png",
    name: "Saut à la corde",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 1 : Échauffements",
    body_part: "Séance Full Body",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/IJPPP5tNWFF3CDwtqe1k.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 30,
    status: 'Tout'

  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/7L37Cw4BePcM1Vu3OD8n.png",
    name: "Montée de genoux",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 1 : Échauffements",
    body_part: "Séance Full Body",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/IJPPP5tNWFF3CDwtqe1k.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 30,
    status: 'Tout'

  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/vekpyA5BwsyfMuqlzXlN.png",
    name: "Étirement cuisse",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 3 : Étirements",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 15,
    status: 'Bas du Corps'

  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/t9SwrEduPuW0B20KEfvG.png",
    name: "Étirement hanches",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 3 : Étirements",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/ZbjVEiZoSnnkgGFwfbGx.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 15,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/b9bPvZiuOHmtXO6Ml8NY.png",
    name: "Étirement dos",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 3 : Étirements",
    body_part: "Séance Haut du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/ZbjVEiZoSnnkgGFwfbGx.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 15,
    status: 'Haut du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/s3KwHMVP1cFRmOPLdLkc.png",
    name: "Hanches & cuisse",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 3 : Étirements",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 15,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/jtVXo58l3qUaJvV98npp.png",
    name: "Étirement cuisse",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 3 : Étirements",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: "30 Secondes",
    repeat: 3,
    recuperation: 15,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/D5ikV24c2DUTBOkbp01R.png",
    name: "Squat",
    description: "C'est un super movement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/MTepHWQlz1OMxwuM7nJV.png",
    name: "Chaise",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/pdMYqw3JV10I5RmG0My1.png",
    name: "Fentes Fixes",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/78IyBh4mICf8cnJR7qZ6.png",
    name: "Jumping Jack",
    description: "C'est un super movement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Full Body",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/IJPPP5tNWFF3CDwtqe1k.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Full Body',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/0pJUzehwE9ueJOiEBJPs.png",
    name: "Squat Sauté",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/VLje1ollRcZBVB17Wo86.png",
    name: "Le Pont",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/TGLS9fZUq9GATAKhCzeb.png",
    name: "Squat Impulsion",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/0fW0aGLlIbWu46MXggZC.png",
    name: "Pont Surélevé",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/3QAkHm83GuxhPnMqjkj0.png",
    name: "Pont Équilibre",
    description: "C'est un super movement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/dw8oKK3jWXeT0Tk7nXBO.png",
    name: "Position du Chien",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    id: uuid.v4(),
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/OCY2COSOBhfG0EmE5Mwu.png",
    name: "Mountain Climber",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/oHDhQYctEcmoG90Y2VgD.png",
    name: "Extension Fessier",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },
  {
    image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/2xVLGxlGa3UOGPsTDXMc/pub/w1sXvu9ZRh0DszsZFrco.png",
    name: "Squat Sumo",
    description: "C'est un super mouvement !",
    infos: "Vous pouvez modifier les quantités et le temps de recuperation plus tard.",
    category: "Partie 2 : Exercices",
    body_part: "Séance Bas du Corps",
    body_image: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/rKHwzU5y7IDSLkW4XHwB/pub/RmhCm8Mb1c8oNQjnJi4e.png",
    movement: 12,
    repeat: 3,
    recuperation: 45,
    status: 'Bas du Corps',
  },


]
